### ISSUE TITLE
Rough conversion of prototype into web app

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/tnc-network-site#3]
Breakdown the prototype into an app. Given the demands of the website, this may not entail bringing in React, and instead using a lighter front-end framework.

**Comment by kellyi** [comment]
Spoke with Casey and we decided to use ES5 + Backbone/Underscore/jQuery since it'll help structure the project without bringing in the overhead of React/Babel/etc. For now I'll set up a mock configuration file that gets read into a Backbone model to hydrate the app.

As part of this and #4 I'm going to try to bring in a linter and any other ES5-compatible pleasant things from our standard project setup, and also set up a Travis build which will run a linter on PRs & develop for now and eventually maybe build and release the app bundle via git flow releases.
